import {
  Sun,
  Moon,
  Laptop,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  Plus,
  Trash,
  User,
  Settings,
  LogOut,
  Loader2,
  X,
  Check,
  Copy,
  AlertTriangle,
  ArrowRight,
  Github,
  Twitter,
  Menu,
} from "lucide-react"

export const Icons = {
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  moreHorizontal: MoreHorizontal,
  plus: Plus,
  trash: Trash,
  user: User,
  settings: Settings,
  logout: LogOut,
  spinner: Loader2,
  close: X,
  check: Check,
  copy: Copy,
  warning: AlertTriangle,
  arrowRight: ArrowRight,
  gitHub: Github,
  twitter: Twitter,
  menu: Menu,
}
